<a href="https://colab.research.google.com/github/Krishal555/Concepts-of-AI-Workshop0/blob/main/Worksheet_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Krishal Maharjan
# Level - 5


#Worksheet 1
#Machine Learning and AI

# Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
import numpy as np
emptyArr = np.empty((2,2))
onesArr = np.ones((4,2))
print("Empty array: \n",emptyArr)
print("Ones array: \n",onesArr)

filledArr1 = np.full((4,2),7)
filledArr2 = np.full((2,2),5)
print("\nFilled value 7(4*2) and 5(2*2) : ")
print(filledArr1,"\n\n",filledArr2)

givenArr = np.array([[1,2],[3,4]])
zeroslikeArr = np.zeros_like(givenArr)
oneslikeArr = np.ones_like(givenArr)
print("\nZeros Like : \n",zeroslikeArr)
print("\nOnes Like : \n",oneslikeArr)

newlist = [1,2,3,4]
numpyArr = np.array(newlist)
print("Converted numpy array: \n",numpyArr)

Empty array: 
 [[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]]
Ones array: 
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Filled value 7(4*2) and 5(2*2) : 
[[7 7]
 [7 7]
 [7 7]
 [7 7]] 

 [[5 5]
 [5 5]]

Zeros Like : 
 [[0 0]
 [0 0]]

Ones Like : 
 [[1 1]
 [1 1]]
Converted numpy array: 
 [1 2 3 4]


# 4.1.1 Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
import numpy as np
arrayRange = np.arange(10,50)
print("Array Range from 10 to 49\n",arrayRange)

matrix = np.arange(9).reshape(3,3)
print("\n3 * 3 Matrix from 0 to 8:\n",matrix)

identityMatrix = np.eye(3,3)
print("\nIdentity matrix of 3 * 3: \n",identityMatrix)

randomArray = np.random.random(30)
meanValue = randomArray.mean()
print(f"\nMean value of it : {meanValue:.2f}")

randomValueArray = np.random.random((10,10))
minValue = randomValueArray.min()
maxValue = randomValueArray.max()

print("\n Random Value 10 * 10 array : \n",randomValueArray)
print(f"\n Minimum Value : {minValue}")
print(f"\n Maximum Value : {maxValue}")

zeroArray = np.zeros(10)
zeroArray[4] = 1
print(zeroArray)

arr = [1,2,0,0,4,0]
reversedArray = arr[::-1]
print("\n Actual array :",arr)
print("\n Reversed Array :",reversedArray)

array1 = np.ones((5,5))
array1[1:-1,1:-1]=0
print("\n",array1)

checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1  # Odd rows, even columns
checkerboard[::2, 1::2] = 1  # Even rows,Odd columns
print("\nCheckerboard Pattern 8x8 Matrix:\n", checkerboard)

Array Range from 10 to 49
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3 * 3 Matrix from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Identity matrix of 3 * 3: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Mean value of it : 0.45

 Random Value 10 * 10 array : 
 [[0.55241068 0.29754981 0.14053931 0.59798209 0.33774739 0.73315014
  0.7292687  0.78983169 0.5450013  0.1208378 ]
 [0.01664494 0.69281161 0.04809317 0.54208922 0.58538119 0.59996164
  0.69977421 0.94169213 0.05965399 0.07190279]
 [0.35097886 0.35027496 0.49191728 0.97084551 0.15416298 0.4505621
  0.88522928 0.62951903 0.23170725 0.8496684 ]
 [0.90181607 0.87329422 0.50714498 0.91066702 0.74217635 0.11013111
  0.7269668  0.54991822 0.83030424 0.06703639]
 [0.14878607 0.84230129 0.9921458  0.27719204 0.60250615 0.17817577
  0.10111525 0.47196973 0.24944228 0.36682822]
 [0.18689035 0.13988387 0.46839492 0.84530305 0.7726029  0.24682094
  0.27688062 0.43094419 0.32

# Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?


In [ ]:
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

print(f"Given,\nX = \n{x}\n")
print(f"Y = \n{y}\n")
print(f"V = \n{v}\n")
print(f"W = \n{w}\n")

addition = x + y
subtraction = y - x
multipcation = x * 2
square = np.square(x)
dot_vw = np.dot(v,w)
dot_xv = np.dot(x,v)
dot_xy = np.dot(x,y)

print(f"The addition of x and y array is \n{addition}\n")
print(f"The subtraction from x to y array is \n{subtraction}\n")
print(f"Multilpying by 2 on all sides \n{multipcation}\n")
print(f"Squaring all the elements\n{square}\n")
print(f"Dot product between V and W : \n{dot_vw}\n")
print(f"Dot product between X and V : \n{dot_xv}\n")
print(f"Dot product between X and Y : \n{dot_xy}\n")

concat_xy = np.concatenate((x,y),axis = 0)
concat_vw = np.vstack((v,w))

print(f"X and Y along row Concatination :\n{concat_xy}\n")
print(f"V and W along column Concatination :\n{concat_vw}\n")



Given,
X = 
[[1 2]
 [3 5]]

Y = 
[[5 6]
 [7 8]]

V = 
[ 9 10]

W = 
[11 12]

The addition of x and y array is 
[[ 6  8]
 [10 13]]

The subtraction from x to y array is 
[[4 4]
 [4 3]]

Multilpying by 2 on all sides 
[[ 2  4]
 [ 6 10]]

Squaring all the elements
[[ 1  4]
 [ 9 25]]

Dot product between V and W : 
219

Dot product between X and V : 
[29 77]

Dot product between X and Y : 
[[19 22]
 [50 58]]

X and Y along row Concatination :
[[1 2]
 [3 5]
 [5 6]
 [7 8]]

V and W along column Concatination :
[[ 9 10]
 [11 12]]



# Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}
• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}

In [ ]:
import numpy as np
a = np.array([[3,4],[7,8]])
b = np.array([[5,3],[2,1]])

## A.A-1 = I
a_inv = np.linalg.inv(a)
identity_matrix = np.dot(a,a_inv)
print(identity_matrix)

## A.B not equals to B.A
AB = np.dot(a, b)
BA = np.dot(b, a)
are_not_equal = not np.array_equal(AB, BA)
print(f"{are_not_equal},A.B is not equals to B.A")

## (A.B)t = Bt. At
AB_T = np.transpose(np.dot(a, b))
BT_AT = np.dot(np.transpose(b), np.transpose(a))
are_equal = np.array_equal(AB_T, BT_AT)
print(f"{are_equal},Transpose of (A.B) is equals to B Transpose .A Transpose")

## A.X = B
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])
B = np.array([-1, -3, 9])

A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
print(f"Solution of Linear equation using Inverse method is \n{x}\n")


[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
True,A.B is not equals to B.A
True,Transpose of (A.B) is equals to B Transpose .A Transpose
Solution of Linear equation using Inverse method is 
[[1 2]
 [3 5]]



# 4.2 Experiment: How Fast is Numpy?
# In this exercise, you will compare the performance and implementation of operations using plain Python
lists (arrays) and NumPy arrays. Follow the instructions:
1. Element-wise Addition:
• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.
2. Element-wise Multiplication

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Mea-
sure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.
3. Dot Product
• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.
4. Matrix Multiplication
• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure
and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

In [1]:
import numpy as np
import time

# 1. Element-wise Addition
# Using Python Lists
list1 = [i for i in range(1000000)]
list2 = [i for i in range(1000000)]

start = time.time()
list_addition = [list1[i] + list2[i] for i in range(len(list1))]
end = time.time()
print(f"Python Lists - Addition: {end - start:.5f} seconds")

# Using NumPy Arrays
arr1 = np.array(list1)
arr2 = np.array(list2)

start = time.time()
numpy_addition = arr1 + arr2
end = time.time()
print(f"NumPy Arrays - Addition: {end - start:.5f} seconds")

# 2. Element-wise Multiplication
# Using Python Lists
start = time.time()
list_multiplication = [list1[i] * list2[i] for i in range(len(list1))]
end = time.time()
print(f"Python Lists - Multiplication: {end - start:.5f} seconds")

# Using NumPy Arrays
start = time.time()
numpy_multiplication = arr1 * arr2
end = time.time()
print(f"NumPy Arrays - Multiplication: {end - start:.5f} seconds")

# 3. Dot Product
# Using Python Lists
start = time.time()
list_dot_product = sum([list1[i] * list2[i] for i in range(len(list1))])
end = time.time()
print(f"Python Lists - Dot Product: {end - start:.5f} seconds")

# Using NumPy Arrays
start = time.time()
numpy_dot_product = np.dot(arr1, arr2)
end = time.time()
print(f"NumPy Arrays - Dot Product: {end - start:.5f} seconds")

# 4. Matrix Multiplication
# Generate 1000x1000 Matrices
matrix1 = [[i for i in range(1000)] for _ in range(1000)]
matrix2 = [[i for i in range(1000)] for _ in range(1000)]

# Using Python Lists
start = time.time()
python_matrix_mult = [[sum(a * b for a, b in zip(row, col)) for col in zip(*matrix2)] for row in matrix1]
end = time.time()
print(f"Python Lists - Matrix Multiplication: {end - start:.5f} seconds")

# Using NumPy Arrays
np_matrix1 = np.array(matrix1)
np_matrix2 = np.array(matrix2)

start = time.time()
numpy_matrix_mult = np.dot(np_matrix1, np_matrix2)
end = time.time()
print(f"NumPy Arrays - Matrix Multiplication: {end - start:.5f} seconds")


Python Lists - Addition: 0.26784 seconds
NumPy Arrays - Addition: 0.00645 seconds
Python Lists - Multiplication: 0.30180 seconds
NumPy Arrays - Multiplication: 0.01048 seconds
Python Lists - Dot Product: 0.28832 seconds
NumPy Arrays - Dot Product: 0.00227 seconds
Python Lists - Matrix Multiplication: 232.38063 seconds
NumPy Arrays - Matrix Multiplication: 1.44019 seconds


# Explanation:


#*   Element-wise Addition:

Using Python lists it iterate through each element, adding corresponding elements whereas using NumPy is used to perform vectorized addition.

#*   Element-wise Multiplication:

using Python lists it iterate through each element, multiplying corresponding elements whereas NumPy is used to perform vectorized multiplication.

#* Dot Product:

Using Python lists we can compute the sum of element-wise products whereas NumPy uses the optimized np.dot function.

# * Matrix Multiplication:

Using Python lists we can use nested loops to calculate the sum of products for corresponding rows and columns whereas Numpy uses the highly optimized np.dot for matrix multiplication.